name: BHop
version: 0.2
description: bhop
author: sooslick
main: ru.sooslick.bhop.Engine
softdepend:
  - WorldEdit
  - WorldGuard
commands:
  bhop:
    description: Play or manage bhop levels
    aliases: bh
    usage: /bhop <commands>
permissions:
  bhop.gameplay:
    default: true
    description: grants access to start, load, exit and continue commands
  bhop.bypass:
    default: op
    description: allows to build ignoring levels restrictions
