name: BHop
version: 0.3.1
description: bhop
author: sooslick
main: ru.sooslick.bhop.Engine
softdepend:
  - WorldEdit
  - WorldGuard
commands:
  bhop:
    description: Play bhop levels
    aliases: bh
    usage: /bhop <commands>
  bhopmanage:
    description: Manage bhop levels
    aliases: bhed
    usage: /bhopmanage <commands> <params>
permissions:
  bhop.gameplay:
    default: true
    description: grants access to start, load, exit and continue commands
  bhop.bypass:
    default: op
    description: allows to build ignoring levels restrictions
  bhop.edit:
    default: op
    description: grants access to editor commands
