name: BHop
version: 0.5.2
description: bhop
author: sooslick
main: ru.sooslick.bhop.Engine
api-version: 1.16
softdepend:
  - WorldEdit
  - WorldGuard
commands:
  bhop:
    description: Play bhop levels
    aliases: bh
    usage: /bhop <commands>
  bhopmanage:
    description: Manage bhop levels
    aliases: bhed, bhm
    usage: /bhopmanage <commands> <params>
permissions:
  bhop.gameplay:
    default: true
    description: grants access to start, load, exit and continue commands
  bhop.bypass:
    default: op
    description: allows to build ignoring levels restrictions
  bhop.edit:
    default: op
    description: grants access to editor commands for all levels
    children:
      bhop.edit.own: true
  bhop.edit.own:
    default: op
    description: grants access to editor commands for sender's levels
